env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  lint_frontend:
    name: lint frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0
      - run: yarn install --immutable

      - run: yarn workspace @liquity/dev-frontend lint

  # doesn't work and the test is very basic anyway
  # test_frontend:
  #   name: test frontend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 22
  #         cache: yarn
  #       env:
  #         # Workaround for https://github.com/actions/setup-node/issues/317
  #         FORCE_COLOR: 0
  #     - run: yarn install --immutable

  #     - run: yarn workspace @liquity/dev-frontend test

  build_frontend:
    name: build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0
      - run: yarn install --immutable

      - run: yarn workspace @liquity/dev-frontend build:tsc
      - run: yarn workspace @liquity/dev-frontend build:vite
